async (page) => {
  const check = (value, message) => { if (!value) throw new Error(message); };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.reload();
  await page.setViewportSize({width:1440,height:1080});
  await page.getByRole('button', {name:'Agreement',exact:true}).click();
  await page.getByRole('button', {name:'Mask document',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('metric-total').textContent === '9');
  const original = await page.getByRole('textbox', {name:'DOCUMENT TEXT',exact:true}).inputValue();
  const masked = await page.locator('#result').textContent();
  check(!masked.includes('Jane Smith') && masked.includes('[CLIENT_1]'), 'Name masking failed');
  check(masked.includes('S&P 500') && masked.includes('$49.00'), 'Financial negative control failed');
  check(await page.locator('#result mark').count() === 9, 'Expected 9 visible entity highlights');
  await page.getByRole('button', {name:'Test completion',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('wire-status').textContent.startsWith('Completion verified'));
  const completion = await page.locator('#payload').textContent();
  check(!completion.includes('Jane Smith') && JSON.parse(completion).messages.length === 1, 'Completion payload failed');
  await page.getByRole('button', {name:'Test embedding',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('wire-status').textContent.startsWith('Embedding verified'));
  check(await page.locator('#metric-wire').textContent() === '2 / 2 verified', 'Both operations must pass');
  check(JSON.parse(await page.locator('#payload').textContent()).input === masked, 'Embedding payload mismatch');
  await page.getByRole('button', {name:'Restore original',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('result-tag').textContent.startsWith('Original'));
  check(await page.locator('#result').textContent() === original, 'Restored source differs from input');
  const restoredNames = await page.locator('#result mark[data-kind=CLIENT]').allTextContents();
  check(restoredNames.length === 3 && restoredNames.every(name => name === 'Jane Smith'), 'Restored highlights incorrect');
  await page.getByRole('button', {name:'Masked',exact:true}).click();
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.getByRole('button', {name:'Copy',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('notice').textContent === 'Masked text copied to clipboard.');
  const clipboard = await page.evaluate(() => navigator.clipboard.readText());
  check(clipboard.replace(/\r\n/g, '\n') === masked.replace(/\r\n/g, '\n'), 'Clipboard must contain masked text');
  await page.locator('#notice').waitFor({state:'hidden'});
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:'output/playwright/desktop-verified.png',fullPage:true});

  await page.getByRole('button', {name:'Clean control',exact:true}).click();
  await page.getByRole('button', {name:'Mask document',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('metric-total').textContent === '0');
  check(await page.locator('#result mark').count() === 0, 'Clean document was flagged');
  check(await page.locator('#result').textContent() === await page.locator('#source').inputValue(), 'Clean text changed');
  await page.getByRole('button', {name:'Edge cases',exact:true}).click();
  await page.getByRole('button', {name:'Mask document',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('result').textContent.includes('[LITERAL_1]'));
  check(await page.locator('#result script').count() === 0, 'Source HTML must not execute');
  await page.getByRole('button', {name:'Restore original',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('result-tag').textContent.startsWith('Original'));
  check(await page.locator('#result').textContent() === await page.locator('#source').inputValue(), 'Unicode roundtrip failed');
  const ssn = await page.locator('#result mark[data-kind=SSN]').textContent();
  check(ssn === '１２３-４５-６７８９', 'Fullwidth SSN highlight mismatch');

  await page.getByRole('button', {name:'Upload TXT document',exact:true}).setInputFiles('fixtures/mixed.txt');
  await page.waitForFunction(() => document.getElementById('source').value.includes('INVESTMENT AGREEMENT'));
  await page.getByRole('button', {name:'Mask document',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('metric-total').textContent === '9');
  await page.setViewportSize({width:390,height:844});
  await page.locator('#notice').waitFor({state:'hidden'});
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile horizontal overflow');
  await page.screenshot({path:'output/playwright/mobile-verified.png',fullPage:true});
  await page.getByRole('button', {name:'Restore original',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('result-tag').textContent.startsWith('Original'));
  await page.getByRole('button', {name:'Delete document',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('result').hidden);
  check(await page.locator('#source').inputValue() === '', 'Delete did not clear input');
  check(await page.getByRole('button', {name:'Test completion',exact:true}).isDisabled(), 'Delete left send enabled');
  check(await page.evaluate(() => localStorage.length === 0 && sessionStorage.length === 0), 'Browser storage should be empty');

  await page.setViewportSize({width:1440,height:1080});
  await page.locator('#notice').waitFor({state:'hidden'});
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.screenshot({path:'output/playwright/desktop-empty.png',fullPage:true});
  check(errors.length === 0, 'Browser errors: ' + errors.join('; '));
  return {status:'PASS',checks:['seven-types','stable-tokens','exact-restore','completion-HTTP','embedding-HTTP','masked-clipboard','clean-control','unicode-highlights','HTML-as-text','TXT-upload','mobile-layout','delete','no-browser-storage'],browserErrors:errors};
}
